package blitra

type Key string

// TODO: this only covers US keyboards. We may need to add more keys for other
// keyboard layouts in the future.
const (
	ControlKey      Key = "control"
	LeftControlKey  Key = "control:left"
	RightControlKey Key = "control:right"
	ShiftKey        Key = "shift"
	LeftShiftKey    Key = "shift:left"
	RightShiftKey   Key = "shift:right"
	AltKey          Key = "alt"
	LeftAltKey      Key = "alt:left"
	RightAltKey     Key = "alt:right"
	SuperKey        Key = "super"
	LeftSuperKey    Key = "super:left"
	RightSuperKey   Key = "super:right"

	InsertKey      Key = "Insert"
	HomeKey        Key = "Home"
	EndKey         Key = "End"
	PageUpKey      Key = "PageUp"
	PageDownKey    Key = "PageDown"
	NumLockKey     Key = "NumLock"
	CapsLockKey    Key = "CapsLock"
	ScrollLockKey  Key = "ScrollLock"
	PauseKey       Key = "Pause"
	PrintScreenKey Key = "PrintScreen"
	BreakKey       Key = "Break"
	ContextMenuKey Key = "ContextMenu"
	BackspaceKey   Key = "Backspace"
	DeleteKey      Key = "Delete"
	UpArrowKey     Key = "ArrowUp"
	DownArrowKey   Key = "ArrowDown"
	LeftArrowKey   Key = "ArrowLeft"
	RightArrowKey  Key = "ArrowRight"
	EscapeKey      Key = "Escape"
	F1Key          Key = "F1"
	F2Key          Key = "F2"
	F3Key          Key = "F3"
	F4Key          Key = "F4"
	F5Key          Key = "F5"
	F6Key          Key = "F6"
	F7Key          Key = "F7"
	F8Key          Key = "F8"
	F9Key          Key = "F9"
	F10Key         Key = "F10"
	F11Key         Key = "F11"
	F12Key         Key = "F12"

	BackTickKey Key = "BackTick"
	OneKey      Key = "1"
	TwoKey      Key = "2"
	ThreeKey    Key = "3"
	FourKey     Key = "4"
	FiveKey     Key = "5"
	SixKey      Key = "6"
	SevenKey    Key = "7"
	EightKey    Key = "8"
	NineKey     Key = "9"
	ZeroKey     Key = "0"
	MinusKey    Key = "-"
	EqualKey    Key = "="

	TildeKey            Key = "~"
	ExclamationKey      Key = "!"
	AtKey               Key = "@"
	HashKey             Key = "#"
	DollarKey           Key = "$"
	PercentKey          Key = "%"
	CaretKey            Key = "^"
	AmpersandKey        Key = "&"
	AsteriskKey         Key = "*"
	OpenParenthesisKey  Key = "("
	CloseParenthesisKey Key = ")"
	UnderscoreKey       Key = "_"
	PlusKey             Key = "+"

	TabKey                Key = "Tab"
	QKey                  Key = "q"
	WKey                  Key = "w"
	EKey                  Key = "e"
	RKey                  Key = "r"
	TKey                  Key = "t"
	YKey                  Key = "y"
	UKey                  Key = "u"
	IKey                  Key = "i"
	OKey                  Key = "o"
	PKey                  Key = "p"
	OpenSquareBracketKey  Key = "["
	CloseSquareBracketKey Key = "]"
	BackslashKey          Key = "\\"

	CapitalQKey          Key = "Q"
	CapitalWKey          Key = "W"
	CapitalEKey          Key = "E"
	CapitalRKey          Key = "R"
	CapitalTKey          Key = "T"
	CapitalYKey          Key = "Y"
	CapitalUKey          Key = "U"
	CapitalIKey          Key = "I"
	CapitalOKey          Key = "O"
	CapitalPKey          Key = "P"
	OpenCurlyBracketKey  Key = "{"
	CloseCurlyBracketKey Key = "}"
	PipeKey              Key = "|"

	AKey          Key = "a"
	SKey          Key = "s"
	DKey          Key = "d"
	FKey          Key = "f"
	GKey          Key = "g"
	HKey          Key = "h"
	JKey          Key = "j"
	KKey          Key = "k"
	LKey          Key = "l"
	SemicolonKey  Key = ";"
	ApostropheKey Key = "'"
	EnterKey      Key = "Enter"

	CapitalAKey    Key = "A"
	CapitalSKey    Key = "S"
	CapitalDKey    Key = "D"
	CapitalFKey    Key = "F"
	CapitalGKey    Key = "G"
	CapitalHKey    Key = "H"
	CapitalJKey    Key = "J"
	CapitalKKey    Key = "K"
	CapitalLKey    Key = "L"
	ColonKey       Key = ":"
	DoubleQuoteKey Key = "\""

	ZKey            Key = "z"
	XKey            Key = "x"
	CKey            Key = "c"
	VKey            Key = "v"
	BKey            Key = "b"
	NKey            Key = "n"
	MKey            Key = "m"
	CommaKey        Key = ","
	PeriodKey       Key = "."
	ForwardSlashKey Key = "/"

	CapitalZKey     Key = "Z"
	CapitalXKey     Key = "X"
	CapitalCKey     Key = "C"
	CapitalVKey     Key = "V"
	CapitalBKey     Key = "B"
	CapitalNKey     Key = "N"
	CapitalMKey     Key = "M"
	LessThanKey     Key = "<"
	GreaterThanKey  Key = ">"
	QuestionMarkKey Key = "?"

	SpaceKey Key = "Space"
)
